# Generated by Django 4.0.4 on 2023-06-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_category_alter_women_photo_women_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Famous woman', 'verbose_name_plural': 'Famous women'},
        ),
    ]
